FROM alpine-jdk:base
MAINTAINER etf
ENTRYPOINT /bin/bash
RUN apk --no-cache add netcat-openbsd
COPY files/Log_Mikroservis-1.0-SNAPSHOT.jar /opt/lib/
#COPY Logovi-entrypoint.sh /opt/bin/Logovi-entrypoint.sh
#RUN chmod 755 /opt/bin/Logovi-entrypoint.sh
#RUN sh /opt/bin/Logovi-entrypoint.sh
EXPOSE 8083
ENTRYPOINT ["/usr/bin/java"]
CMD ["-jar", "/opt/lib/Log_Mikroservis-1.0-SNAPSHOT.jar"]
