FROM alpine-jdk:base
MAINTAINER etf
COPY files/nwt_tim14_eureka_server-1.0-SNAPSHOT.jar /opt/lib/
ENTRYPOINT ["/usr/bin/java"]
CMD ["-jar", "/opt/lib/nwt_tim14_eureka_server-1.0-SNAPSHOT.jar"]
EXPOSE 8761