FROM anapsix/alpine-java
MAINTAINER etf
RUN apk --no-cache add netcat-openbsd
COPY files/Putovanje-mikroservis-1.0.0-SNAPSHOT.jar /opt/lib/
#ENTRYPOINT ["/usr/bin/java"]
CMD ["java", "-jar", "/opt/lib/Putovanje-mikroservis-1.0.0-SNAPSHOT.jar"]
EXPOSE 8081
